= Bien Venue
Tom Crowley <tomocrowley@gmail.com>
:imagesdir: https://raw.githubusercontent.com/Tomocrowley/images/master/


Picking a venue always felt like it was going to be a big part of planning the wedding. If Tom and Emma wanted a wedding that felt personal and 'us', it needed to be in the right place.

The https://www.thepriory.net/[Priory] was the first venue they visited and they loved everything about it. they didn't want to just jump at the first thing they saw, though, so they went and looked around a similar place the following week.

Even though the second venue, the name of which escapes me, had live animals (one wedding's cute entertainment, another wedding's food) and the owner sent us home with a big bag of fresh vegetables they had grown onsite, it was just too big, almost too commercial. It lacked the homely, everything under one roof feel of The Priory.

Now they'd seen at least one other venue, they felt justified in going for our first choice, so they got back in touch with Karen at The Priory and booked in.

Some venues are too small, some venues are too big, but for our goldy-locked Bride, this venue was just right. It had room outside for guests to wander (and had the weather not started terrible, they would have held the ceremony outside too), and was big enough inside that everyone could stay in the same room all evening.



All being under one roof was important to us.
